services:
  mysql:
    image: mysql:lts
    container_name: home_iot_db
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ${DUMP_PATH}:/docker-entrypoint-initdb.d/start.sql
    networks:
      - home_iot_net

  goapi:
    image: crisurbina/home_sensor_api:latest
    container_name: go_api
    ports:
      - "${API_PORT}:8080"
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    networks:
      - home_iot_net
    depends_on:
      - mysql

volumes:
  mysql_data:

networks:
  home_iot_net:
    name: home_iot_net
