services:
  mysql:
    image: mysql:8.0.42
    container_name: mysql_8_0_42
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_USER: cristian
      MYSQL_PASSWORD: cris2001
      MYSQL_DATABASE: home_iot
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  goapi:
    build:
      context: .
    container_name: go_api
    ports:
      - "8080:8080"
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: cristian
      DB_PASSWORD: cris2001
      DB_NAME: home_iot
    depends_on:
      - mysql

volumes:
  mysql_data:
