services:
  mysql:
    image: mysql:lts
    container_name: home_iot_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_USER: cristian
      MYSQL_PASSWORD: cris2001
      MYSQL_DATABASE: home_iot
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - home_iot_net

  goapi:
    build:
      context: .
    container_name: go_api
    ports:
      - "8080:8080"
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: cristian
      DB_PASSWORD: cris2001
      DB_NAME: home_iot
    networks:
      - home_iot_net
    depends_on:
      - mysql

volumes:
  mysql_data:

networks:
  home_iot_net:
    name: home_iot_net
