// Code generated by MockGen. DO NOT EDIT.
// Source: internal/application/mediator.go
//
// Generated by this command:
//
//	mockgen -source=internal/application/mediator.go -destination=internal/application/mocks/mediator_mock.go -package=appmocks
//

// Package appmocks is a generated GoMock package.
package appmocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockMediator is a mock of Mediator interface.
type MockMediator struct {
	ctrl     *gomock.Controller
	recorder *MockMediatorMockRecorder
	isgomock struct{}
}

// MockMediatorMockRecorder is the mock recorder for MockMediator.
type MockMediatorMockRecorder struct {
	mock *MockMediator
}

// NewMockMediator creates a new mock instance.
func NewMockMediator(ctrl *gomock.Controller) *MockMediator {
	mock := &MockMediator{ctrl: ctrl}
	mock.recorder = &MockMediatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMediator) EXPECT() *MockMediatorMockRecorder {
	return m.recorder
}

// Send mocks base method.
func (m *MockMediator) Send(ctx context.Context, query any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Send", ctx, query)
	ret0, _ := ret[0].(error)
	return ret0
}

// Send indicates an expected call of Send.
func (mr *MockMediatorMockRecorder) Send(ctx, query any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Send", reflect.TypeOf((*MockMediator)(nil).Send), ctx, query)
}
