// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/domain/reading_repository.go
//
// Generated by this command:
//
//	mockgen -source=./internal/domain/reading_repository.go -destination=./internal/application/mocks/reading_repository_mock.go -package=appmocks
//

// Package appmocks is a generated GoMock package.
package appmocks

import (
	context "context"
	domain "cristianUrbina/water_level_sensor_system/internal/domain"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockIReadingRepository is a mock of IReadingRepository interface.
type MockIReadingRepository struct {
	ctrl     *gomock.Controller
	recorder *MockIReadingRepositoryMockRecorder
	isgomock struct{}
}

// MockIReadingRepositoryMockRecorder is the mock recorder for MockIReadingRepository.
type MockIReadingRepositoryMockRecorder struct {
	mock *MockIReadingRepository
}

// NewMockIReadingRepository creates a new mock instance.
func NewMockIReadingRepository(ctrl *gomock.Controller) *MockIReadingRepository {
	mock := &MockIReadingRepository{ctrl: ctrl}
	mock.recorder = &MockIReadingRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIReadingRepository) EXPECT() *MockIReadingRepositoryMockRecorder {
	return m.recorder
}

// Add mocks base method.
func (m *MockIReadingRepository) Add(ctx context.Context, s domain.SensorReading) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Add", ctx, s)
	ret0, _ := ret[0].(error)
	return ret0
}

// Add indicates an expected call of Add.
func (mr *MockIReadingRepositoryMockRecorder) Add(ctx, s any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Add", reflect.TypeOf((*MockIReadingRepository)(nil).Add), ctx, s)
}
