// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/domain/sensor_repository.go
//
// Generated by this command:
//
//	mockgen -source=./internal/domain/sensor_repository.go -destination=./internal/application/mocks/sensor_repository_mock.go -package=appmocks
//

// Package appmocks is a generated GoMock package.
package appmocks

import (
	context "context"
	domain "cristianUrbina/water_level_sensor_system/internal/domain"
	reflect "reflect"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockISensorRepository is a mock of ISensorRepository interface.
type MockISensorRepository struct {
	ctrl     *gomock.Controller
	recorder *MockISensorRepositoryMockRecorder
	isgomock struct{}
}

// MockISensorRepositoryMockRecorder is the mock recorder for MockISensorRepository.
type MockISensorRepositoryMockRecorder struct {
	mock *MockISensorRepository
}

// NewMockISensorRepository creates a new mock instance.
func NewMockISensorRepository(ctrl *gomock.Controller) *MockISensorRepository {
	mock := &MockISensorRepository{ctrl: ctrl}
	mock.recorder = &MockISensorRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockISensorRepository) EXPECT() *MockISensorRepositoryMockRecorder {
	return m.recorder
}

// GetByID mocks base method.
func (m *MockISensorRepository) GetByID(ctx context.Context, ID uuid.UUID) (domain.Sensor, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, ID)
	ret0, _ := ret[0].(domain.Sensor)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockISensorRepositoryMockRecorder) GetByID(ctx, ID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockISensorRepository)(nil).GetByID), ctx, ID)
}
